# Rust 格式化配置
edition = "2021"
max_width = 100
tab_spaces = 4
newline_style = "Unix"
use_small_heuristics = "Default"
reorder_imports = true
reorder_modules = true
remove_nested_parens = true
format_strings = true
wrap_comments = true
comment_width = 100
normalize_comments = true
normalize_doc_attributes = true
format_code_in_doc_comments = true
format_macro_matchers = true
format_macro_bodies = true
empty_item_single_line = true
struct_lit_single_line = true
fn_single_line = false
where_single_line = false
imports_indent = "Block"
imports_layout = "HorizontalVertical"
merge_imports = true
reorder_impl_items = true
use_field_init_shorthand = true
use_try_shorthand = true
use_self = true
type_punctuation_density = "Wide"
space_before_colon = false
space_after_colon = true
spaces_around_ranges = false
binop_separator = "Front"
hex_literal_case = "Upper"
type_alias_bounds_suppression = false
enum_discrim_align_threshold = 0
match_arm_blocks = true
match_arm_leading_pipes = "Never"
force_multiline_blocks = false
fn_args_layout = "Tall"
brace_style = "SameLineWhere"
control_brace_style = "AlwaysSameLine"
trailing_semicolon = true
trailing_comma = "Vertical"
match_block_trailing_comma = true
blank_lines_upper_bound = 1
blank_lines_lower_bound = 0
edition_2018_idioms = true
version = "Two"
inline_attribute_width = 0
format_generated_files = true
hide_parse_errors = false
error_on_line_overflow = false
error_on_unformatted = false
report_todo = "Never"
report_fixme = "Never"
unstable_features = false
disable_all_formatting = false
skip_children = false
combine_control_expr = true
hard_tabs = false
force_explicit_abi = true
