[package]
name = "quantum-safe-proxy"
version = "0.1.0"
edition = "2021"
description = "PQC-Enabled Sidecar with Hybrid Certificate Support"
authors = ["Jerry <vp780412@gmail.com>"]
license = "MIT"
repository = "https://github.com/JerryR7/quantum-safe-proxy"
keywords = ["proxy", "tls", "pqc", "quantum", "security"]
categories = ["network-programming", "cryptography"]
readme = "README.md"

# Main program entry point
[[bin]]
name = "quantum-safe-proxy"
path = "src/main.rs"

[dependencies]
# Asynchronous runtime
tokio = { version = "1.44.2", features = ["full"] }

# TLS and OpenSSL support
openssl = "0.10.72"
tokio-openssl = "0.6.5"

# Logging
log = "0.4.27"
env_logger = "0.11.3"

# Command-line argument parsing
clap = { version = "4.5.35", features = ["derive"] }

# Configuration file handling
config = "0.15.11"
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.114"

# Error handling
thiserror = "1.0.58"
anyhow = "1.0.81"

[dev-dependencies]
# Testing tools
mockall = "0.12.1"
serial_test = "3.0.0"
tempfile = "3.10.1"

[profile.release]
# Release mode optimizations
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"
strip = true

[profile.dev]
# Development mode optimizations
opt-level = 0
debug = true
