services:
  quantum-safe-proxy:
    image: quantum-safe-proxy:openssl35
    ports:
      - "8443:8443"
    volumes:
      - ./certs:/app/certs
      - ./config:/app/config
      - ./scripts:/app/scripts
    environment:
      - RUST_LOG=debug
      - LD_LIBRARY_PATH=/opt/openssl35/lib64:/opt/openssl35/lib
      - OPENSSL_DIR=/opt/openssl35
      - OPENSSL_LIB_DIR=/opt/openssl35/lib64
      - OPENSSL_INCLUDE_DIR=/opt/openssl35/include
      - RUST_BACKTRACE=1
      - AUTO_GENERATE_CERTS=true
    command: [
      "--listen", "0.0.0.0:8443",
      "--target", "backend:6000",
      "--cert", "/app/certs/hybrid/ml-dsa-87/server.crt",
      "--key", "/app/certs/hybrid/ml-dsa-87/server.key",
      "--ca-cert", "/app/certs/hybrid/ml-dsa-87/ca.crt",
      "--log-level", "debug",
      "--client-cert-mode", "optional"
    ]
    networks:
      - proxy-network
    restart: unless-stopped
    depends_on:
      - backend

  backend:
    image: nginx:alpine
    container_name: backend-service
    volumes:
      - ./docker/nginx/html:/usr/share/nginx/html
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "6000:6000"
    networks:
      - proxy-network
    restart: unless-stopped

networks:
  proxy-network:
    driver: bridge
