services:
  quantum-safe-proxy:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: quantum-safe-proxy:latest
    container_name: quantum-safe-proxy
    ports:
      - "8443:8443"
    volumes:
      - ../certs:/app/certs
    command: >
      --listen 0.0.0.0:8443
      --target backend:6000
      --cert /app/certs/hybrid/dilithium3/server.crt
      --key /app/certs/hybrid/dilithium3/server.key
      --ca-cert /app/certs/hybrid/dilithium3/ca.crt
      --log-level info
      --client-cert-mode required
    networks:
      - proxy-network
    restart: unless-stopped
    depends_on:
      - backend

  backend:
    image: nginx:alpine
    container_name: backend-service
    volumes:
      - ./nginx/html:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "6000:6000"
    networks:
      - proxy-network
    restart: unless-stopped

networks:
  proxy-network:
    driver: bridge
