services:
  quantum-proxy:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: quantum-proxy:latest
    container_name: quantum-proxy
    ports:
      - "8443:8443"
    volumes:
      - ../certs:/app/certs
    command: >
      --listen 0.0.0.0:8443
      --target backend:6000
      --cert /app/certs/server.crt
      --key /app/certs/server.key
      --ca-cert /app/certs/ca.crt
      --log-level info
    networks:
      - proxy-network
    restart: unless-stopped
    depends_on:
      - backend

  backend:
    image: nginx:alpine
    container_name: backend-service
    volumes:
      - ./nginx/html:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    expose:
      - "6000"
    networks:
      - proxy-network
    restart: unless-stopped

networks:
  proxy-network:
    driver: bridge
